### ISSUE TITLE
SAV-G: Invalid Term End Date

### ISSUE THREAD

**Issue by neliaser** [neliaser/pri-reports#11]
Ver 3.0 of the SAV-G seems to give invalid term end dates for (some?) gas reports. Here's Heritage at Millennium Park from Apr 2020-Mar 2021:

![InvalidTermEndDate](https://user-images.githubusercontent.com/82979133/127347013-c7ab3fc6-5218-4281-95a6-18124cbf34f8.png)

**Comment by chaimgertsberg** [comment]
This should be fixed now, but I realized I am not sure what to put into the spp_line_name field when inserting into report_summary_sav if there is more than one spp_line_name.

**Comment by neliaser** [comment]
Glad the issue here is fixed. I'm going to close it. // As for the spp_line_name one, let's talk about that in the Ag. ticket, #5.

**Comment by neliaser** [comment]
Glad the issue here is fixed. I'm going to close it. // As for the spp_line_name one, let's talk about that in the Ag. ticket, #5.
