### ISSUE TITLE
Issues with Excel Templates

### ISSUE THREAD

**Issue by neliaser** [neliaser/pri-reports#13]
You requested that I "simplify" the Excel Templates so that the Python code doesn't run into trouble. I'm not sure if I've hit upon the particular issue you have or not, but before I modify them, let's ensure we're on the same "page" with respect to the problem.

The big "advanced feature" used in those templates are Excel's Tables, a feature meant to automate calculations down entire columns: when a formula is updated in one cell, it (by preferences) can autopopulate down the entire table. The table also autoformats rows in alternating colors.

openpyxl has a description of how it deals with tables: https://openpyxl.readthedocs.io/en/stable/worksheet_tables.html

That might take care of all of the issues you've been facing, but if not, please comment and change the ownership of this ticket back to me. Thanks!

**Comment by chaimgertsberg** [comment]
I did a lot of digging about this, and unfortunately the openpyxl documentation regarding tables is pretty sparse. I ended up using the COM interface, just like I did with PowerShell and it works great.
