### ISSUE TITLE
SAV-G Sometimes Missing WACOG in csv file (and thus in Excel/PDF)

### ISSUE THREAD

**Issue by neliaser** [neliaser/pri-reports#2]
We ran SAV-G on both 400 Condo Association and 155 Harbor Dr Condo Assn. The one for 400 CA looked fine, but the 155 Harbor Dr one was missing the WACOG at the bottom of the file in the CSV, and thus missing it in the Excel/PDF files, giving a 0 value to gas left in storage.

**Comment by chaimgertsberg** [comment]
When you have a moment, can you try the code from the branch created from this issue?

**Comment by neliaser** [comment]
Looks good! Thanks!
