### ISSUE TITLE
Validate that SAV-E Custom Months Works

### ISSUE THREAD

**Issue by neliaser** [neliaser/pri-reports#9]
Using 2.2 SAV-E (for Grand Victoria Casino), when I put 7 in for custom months, I get no months/prices in the dropdown, and the error message in PowerShell indicates

> Method invocation failed because [System.DBNull] does not contain a method named 'ToShortDateString'.
> At M:\Templates\Reports\Savings Analyses\SavingsAnalysis 2.2.2.ps1:1062 char:17
> + ...             $Name = $PotentialLock.date_pr.ToShortDateString() + " -  ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
>     + FullyQualifiedErrorId : MethodNotFound

![image](https://user-images.githubusercontent.com/82979133/126196637-2a8aaa31-8863-4ebe-aa97-4e2641c17434.png)

**Comment by chaimgertsberg** [comment]
This should be fixed now

**Comment by neliaser** [comment]
The updated version just shows the single market price for that number of months ago, rather than the dropdown including all of the market prices over that period. Contrast these two screen captures:
![image](https://user-images.githubusercontent.com/82979133/127556937-cd7a4396-e11c-49e0-b09c-f3881762ad41.png)
![image](https://user-images.githubusercontent.com/82979133/127557005-979d075a-2076-46ee-bac1-a08d0e0067e1.png)

**Comment by chaimgertsberg** [comment]
From what I understood, the point of having the custom months was to be able to choose a specific month, so just that month is shown. I looked back at some old versions and that is the way it worked in the past. If we want to show more months, which months should they be? Should it be two months before, and two months after?

**Comment by neliaser** [comment]
OK; I misremembered how this had worked. My idea of how I thought it worked might have been slightly helpful, but it's not worth coding it.

Sorry, and thanks.
